---
title: "Research"
---

Articles

- Iseki, T., Shigemura, S., Ikeda, S., & Ishima, H. 2024. Does Cooperation with Multiple Actors Diffuse the Government’s Responsibility in the Implementation of COVID-19 Measures? Social Science Japan Journal, 27(1), 77-90.

- Ishima, H. 2024. Talking Like Opposition Parties? Electoral Proximity and Language Styles Employed by Coalition Partners in a Mixed-Member Majoritarian System. Legislative Studies Quarterly, 49 (3) pp.721-740.

- Shigemura, S., Iseki, T., Ikeda, S., & Ishima, H. 2021. Public Support for the Judicial Branches under the COVID-19 Pandemic. Journal of Elections, Public Opinion and Parties, 31(sup1), 348-360.

- Hijino, K. V. L., & Ishima, H. 2021. Multi-level muddling: Candidate Strategies to "Nationalize" Local Elections. Electoral Studies, 70, 102281.

- Ishima, H. 2020. How Electoral Reform Alters Legislative Speech: Evidence from the Parliament of Victoria, Australia 1992–2017. Electoral Studies, 67, 102192.

Articles in Japanese Journals

- Ashitani, K., & Ishima, H. 2025. Parliamentary Debates on the Constitution: How Politicians Have addressed It. Japanese Journal of Electoral Studies, 41 (1), 37-49.

- Ishima, H. 2025. What We Talk about When We Talk about the LDP. Kyoto Law Review. 196 (4/5/6), pp.540-563.

- Ishima, H., Nishimura, T., Iseki, T., and Hakiai, D. 2025. Political Finance Parties without a Political Party. Japanese Journal of Electoral Studies. 40 (2), 130-137

- Ishima, H. 2024. Policy Affairs Research Council From a Comparative Perspective: comparative case studies of Australia and the UK, in Kentaro Oku, Yuichiro Shimizu, and Shinsuke Hamamoto, eds. Policy Affairs Research Council and Japanese Party Politics, Yoshida Shoten.

- Hijino, KVL.& Ishima, H. Blaming, Claiming Credit, or Rallying across Levels: Subnational Candidate Strategies during the Covid-19 Crisis in Japan,  Japanese Journal of Electoral Studies, 39 (1), 51-66.


- Ishima, H. & Tatebayashi, M. 2020. Party Organization and Bicameralism: How Do Members of the House of Councilors Behave within Party Policy Committees? Japanese Journal of Electoral Studies, 36 (1), 35-48.


- Ishima, H. 2019. Where's the Parliamentary Party? A Review Article About Party Organization, Kyoto Law Review.


- Ishima, H. 2018. Parliamentary Party Organizations and Bicameral Legislatures: A Comparison of Japan and Australia. Japanese Journal of Electoral Studies, 34(2), 47-57.


- Ishima, H. 2017. Party Unity and Intra-Party Coordination: The Case of the Australian Labor Party, The Annuals of the Japanese Political Science Association. 68 (1), 134-158.